<?php

/**
 * The equals() methods on the schema value objects were almost entirely
 * uncovered. They are the last line of defence when comparing schemas, so a
 * silent bug in one of them would make verification pass on a real mismatch.
 */

use MigrationSquash\Schema\Column;
use MigrationSquash\Schema\ForeignKey;
use MigrationSquash\Schema\Index;
use MigrationSquash\Schema\Table;

function makeColumn(array $overrides = []): Column
{
    return new Column(
        name: $overrides['name'] ?? 'email',
        type: $overrides['type'] ?? 'varchar',
        nullable: $overrides['nullable'] ?? false,
        default: $overrides['default'] ?? null,
        length: $overrides['length'] ?? 255,
        unsigned: $overrides['unsigned'] ?? false,
        collation: $overrides['collation'] ?? null,
        autoIncrement: $overrides['autoIncrement'] ?? false,
        allowedValues: $overrides['allowedValues'] ?? [],
    );
}

test('Column::equals is true for identical columns', function () {
    expect(makeColumn()->equals(makeColumn()))->toBeTrue();
});

test('Column::equals is false when any single attribute differs', function (string $attribute, mixed $value) {
    expect(makeColumn()->equals(makeColumn([$attribute => $value])))->toBeFalse();
})->with([
    ['name', 'username'],
    ['type', 'text'],
    ['nullable', true],
    ['default', 'x'],
    ['length', 120],
    ['unsigned', true],
    ['collation', 'utf8mb4_bin'],
    ['autoIncrement', true],
    ['allowedValues', ['a', 'b']],
]);

test('Index::equals compares name, type, columns and options', function () {
    $index = new Index('users_email_unique', 'unique', ['email'], null);

    expect($index->equals(new Index('users_email_unique', 'unique', ['email'], null)))->toBeTrue()
        ->and($index->equals(new Index('other_name', 'unique', ['email'], null)))->toBeFalse()
        ->and($index->equals(new Index('users_email_unique', 'index', ['email'], null)))->toBeFalse()
        ->and($index->equals(new Index('users_email_unique', 'unique', ['email', 'id'], null)))->toBeFalse()
        ->and($index->equals(new Index('users_email_unique', 'unique', ['email'], ['x' => 1])))->toBeFalse();
});

test('Index::fromDb maps the normalized keys', function () {
    $index = Index::fromDb([
        'key_name' => 'posts_user_id_index',
        'index_type' => 'index',
        'columns' => ['user_id'],
    ]);

    expect($index->name)->toBe('posts_user_id_index')
        ->and($index->type)->toBe('index')
        ->and($index->columns)->toBe(['user_id'])
        ->and($index->options)->toBeNull();
});

test('ForeignKey::equals ignores the constraint name on purpose', function () {
    $fk = new ForeignKey('posts_user_id_foreign', 'user_id', 'users', 'id', null, 'CASCADE');

    // Constraint names are generated by the database and differ between
    // drivers, so two foreign keys with the same shape are equal whatever
    // they are called. This mirrors the signature-based comparison in
    // SchemaComparator; if it ever changes, both must change together.
    expect($fk->equals(new ForeignKey('a_different_name', 'user_id', 'users', 'id', null, 'CASCADE')))->toBeTrue();
});

test('ForeignKey::equals compares every attribute that describes the relationship', function () {
    $fk = new ForeignKey('posts_user_id_foreign', 'user_id', 'users', 'id', null, 'CASCADE');

    expect($fk->equals(new ForeignKey('posts_user_id_foreign', 'user_id', 'users', 'id', null, 'CASCADE')))->toBeTrue()
        ->and($fk->equals(new ForeignKey('posts_user_id_foreign', 'author_id', 'users', 'id', null, 'CASCADE')))->toBeFalse()
        ->and($fk->equals(new ForeignKey('posts_user_id_foreign', 'user_id', 'authors', 'id', null, 'CASCADE')))->toBeFalse()
        ->and($fk->equals(new ForeignKey('posts_user_id_foreign', 'user_id', 'users', 'uuid', null, 'CASCADE')))->toBeFalse()
        ->and($fk->equals(new ForeignKey('posts_user_id_foreign', 'user_id', 'users', 'id', 'CASCADE', 'CASCADE')))->toBeFalse()
        ->and($fk->equals(new ForeignKey('posts_user_id_foreign', 'user_id', 'users', 'id', null, 'SET NULL')))->toBeFalse();
});

test('Table::equals is true for identically built tables', function () {
    $build = function (): Table {
        return (new Table('users'))
            ->addColumn(makeColumn(['name' => 'id', 'type' => 'bigint', 'autoIncrement' => true]))
            ->addColumn(makeColumn())
            ->addIndex(new Index('users_email_unique', 'unique', ['email'], null))
            ->addForeignKey(new ForeignKey('users_team_id_foreign', 'team_id', 'teams', 'id', null, null));
    };

    expect($build()->equals($build()))->toBeTrue();
});

test('Table::equals is false on a name, column, index or foreign key difference', function () {
    $base = (new Table('users'))
        ->addColumn(makeColumn())
        ->addIndex(new Index('users_email_unique', 'unique', ['email'], null))
        ->addForeignKey(new ForeignKey('fk', 'team_id', 'teams', 'id', null, null));

    $differentName = (new Table('members'))
        ->addColumn(makeColumn())
        ->addIndex(new Index('users_email_unique', 'unique', ['email'], null))
        ->addForeignKey(new ForeignKey('fk', 'team_id', 'teams', 'id', null, null));

    $extraColumn = (new Table('users'))
        ->addColumn(makeColumn())
        ->addColumn(makeColumn(['name' => 'extra']))
        ->addIndex(new Index('users_email_unique', 'unique', ['email'], null))
        ->addForeignKey(new ForeignKey('fk', 'team_id', 'teams', 'id', null, null));

    $differentColumn = (new Table('users'))
        ->addColumn(makeColumn(['name' => 'username']))
        ->addIndex(new Index('users_email_unique', 'unique', ['email'], null))
        ->addForeignKey(new ForeignKey('fk', 'team_id', 'teams', 'id', null, null));

    $differentIndex = (new Table('users'))
        ->addColumn(makeColumn())
        ->addIndex(new Index('other', 'index', ['email'], null))
        ->addForeignKey(new ForeignKey('fk', 'team_id', 'teams', 'id', null, null));

    $noForeignKey = (new Table('users'))
        ->addColumn(makeColumn())
        ->addIndex(new Index('users_email_unique', 'unique', ['email'], null));

    expect($base->equals($differentName))->toBeFalse()
        ->and($base->equals($extraColumn))->toBeFalse()
        ->and($base->equals($differentColumn))->toBeFalse()
        ->and($base->equals($differentIndex))->toBeFalse()
        ->and($base->equals($noForeignKey))->toBeFalse();
});

test('Table::getColumns returns the columns in insertion order', function () {
    $table = (new Table('users'))
        ->addColumns([
            makeColumn(['name' => 'id']),
            makeColumn(['name' => 'email']),
            makeColumn(['name' => 'created_at']),
        ]);

    expect(array_map(fn (Column $c) => $c->name, $table->getColumns()))
        ->toBe(['id', 'email', 'created_at']);
});
